FROM node:alpine
WORKDIR /usr/src/app

RUN apk add --no-cache python3 make g++

COPY Server .

COPY id1 ./id1

EXPOSE 80/tcp
EXPOSE 80/udp

RUN npm install websocket
ENTRYPOINT [ "node", "WebQDS.js", "-port", "80" ]
